POST http://localhost:3003/estudante
Content-Type: application/json

{
    "nome":"Estudante Teste",
    "email": "estudanteTest@email.com",
    "dataNasc": "1998-05-25",
    "turmaId": "implementar posteriormente",
    "hobbies": "['hobbie1', 'hobbie2', 'hobbie3']"
}

###
GET http://localhost:3003/estudante/testeNome

###
POST http://localhost:3003/estudante/mudar-turma/idDoestudante
Content-Type: application/json

{
    "turmaId": "idDaTurma"
}

###
Get http://localhost:3003/docente

###
POST http://localhost:3003/docente
Content-Type: application/json

{
    "nome": "Nome Docente teste",
    "email": "docente@email.com",
    "dataNasc": "01/01/1981",
    "turmaId": "id da Turma"
}

###
POST  http://localhost:3003/docente/mudar-turma/idDoDocente
Content-Type: application/json

{
    "turmaId": "id da nova turma"
}

###
POST  http://localhost:3003/criar-turma
Content-Type: application/json

{
    "id":"001",
    "nome": "freire",
    "modulo": "1"
}