POST http://localhost:3003/estudante
Content-Type: application/json

{
    "nome":"Rafael Correia",
    "email": "rafael@email.com",
    "dataNasc": "31/07/1975",
    "turmaId": "1662843854152"
}

###
GET http://localhost:3003/estudante/Rafael%20Correia

###
POST http://localhost:3003/estudante/mudar-turma/1662846764464
Content-Type: application/json

{
    "turmaId": "1662843854152"
}

###
Get http://localhost:3003/docente

###
POST http://localhost:3003/docente
Content-Type: application/json

{
    "nome": "Gustavo Monteiro",
    "email": "gustavo@email.com",
    "dataNasc": "05/11/1971",
    "turmaId": "1662843854152"
}

###
POST  http://localhost:3003/docente/mudar-turma/1662847913737
Content-Type: application/json

{
    "turmaId": "1662843854152"
}

###
POST  http://localhost:3003/criar-turma
Content-Type: application/json

{
    "id":"001",
    "nome": "freire",
    "modulo": "1"
}